# 100 numpy exercises


[link text](https://)#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SI

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector=np.zeros([],dtype=int)
null_vector

array(0)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
x=np.array([100,28,286])
print("memory size of NumPy array:", x.nbytes)


memory size of NumPy array: 24


In [ ]:
print((A.size*A.itemsize))

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector2=np.zeros((10),dtype=int)
null_vector2[4]=1
null_vector2

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.flip(B)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
C = np.arange(0,9).reshape(3,3)
print(C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
D = np.array ([1,2,0,0,4,0])
np.nonzero(D)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
array_2D = np.identity(3)
print('3*3 matrix:')
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
E = np.eye((3))
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.59735998 0.31097877 0.86823997]
  [0.55422243 0.06053339 0.08192395]
  [0.53190773 0.77896527 0.9193297 ]]

 [[0.90481043 0.28823327 0.46201137]
  [0.33874258 0.04065276 0.56712236]
  [0.48522959 0.34733633 0.73966165]]

 [[0.3494464  0.69134508 0.27432726]
  [0.93238128 0.4587347  0.03366449]
  [0.30280289 0.68127702 0.80835015]]]


In [ ]:
F = np.random.rand(3,3,3)
F

array([[[0.24467222, 0.37645532, 0.49256325],
        [0.67463352, 0.87610784, 0.28872374],
        [0.30130077, 0.32802505, 0.45615764]],

       [[0.35984476, 0.20198087, 0.73342081],
        [0.24229549, 0.61837231, 0.00945299],
        [0.39185915, 0.45068612, 0.95909556]],

       [[0.0951748 , 0.39008485, 0.4412324 ],
        [0.22583075, 0.1980388 , 0.73873241],
        [0.54445055, 0.71127608, 0.00508187]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
G = np.random.rand(10,10)
print(G)
gmin = np.min(G)
print(gmin)
gmax = np.max(G)
print(gmax)

[[0.09170931 0.43602944 0.48269752 0.73115134 0.35554044 0.48811827
  0.46303157 0.75530761 0.76478385 0.46727769]
 [0.63021844 0.13681679 0.47982138 0.61292548 0.93600766 0.60382271
  0.19005064 0.25528605 0.87420536 0.91204046]
 [0.7135286  0.71248546 0.61944609 0.57593511 0.09543646 0.39768356
  0.11778785 0.22073802 0.60788087 0.27423115]
 [0.86696849 0.06970347 0.05092156 0.75442722 0.67755748 0.66351382
  0.89083813 0.72857191 0.67189628 0.82084708]
 [0.43799228 0.57252909 0.53772973 0.21009195 0.80702555 0.00697324
  0.76432374 0.08825502 0.29541499 0.46631972]
 [0.85353899 0.27956754 0.22594947 0.40324121 0.29749684 0.2656937
  0.79792126 0.84896224 0.63493697 0.8046746 ]
 [0.82165418 0.84125211 0.42660061 0.33661939 0.59778221 0.7664555
  0.29971477 0.34364725 0.49101335 0.83573523]
 [0.03308068 0.12846239 0.60939926 0.05714888 0.39152151 0.41781347
  0.53866354 0.26477286 0.27220599 0.86877723]
 [0.83350618 0.43089081 0.50730015 0.49331474 0.96227627 0.79801939
  0.24294931 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
H = np.random.random(30)
print(H)
mean = np.mean(H)
print(H)

[0.18801258 0.38243911 0.06140572 0.91051686 0.36722721 0.96990399
 0.52224022 0.29577313 0.37602371 0.8414448  0.46864897 0.80329397
 0.2179168  0.70901815 0.21688685 0.10063593 0.44571854 0.51678517
 0.63708752 0.87151789 0.23216999 0.55331278 0.92007554 0.75427808
 0.61423983 0.5675605  0.30739504 0.84374914 0.87265784 0.61698304]
[0.18801258 0.38243911 0.06140572 0.91051686 0.36722721 0.96990399
 0.52224022 0.29577313 0.37602371 0.8414448  0.46864897 0.80329397
 0.2179168  0.70901815 0.21688685 0.10063593 0.44571854 0.51678517
 0.63708752 0.87151789 0.23216999 0.55331278 0.92007554 0.75427808
 0.61423983 0.5675605  0.30739504 0.84374914 0.87265784 0.61698304]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
I = np.ones((10,10))
print(I)
I[1:-1,1:-1]=0
print(I)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
II = np.ones((10,10))
#G=np.zeros((12,12))
#G[1:-1,1:-1]=II
#G
II[:,[0,-1]]=0
II[[0,-1],:]=0
print(II)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
(0 * np.nan)
(np.nan == np.nan)
(np.inf > np.nan)
np.nan - np.nan
np.nan in set([np.nan])
(0.3 == 3 * 0.1)

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
x = np.zeros((5,5))
print(x)
x[1,0]=1
x[2,1]=2
x[3,2]=3
x[4,3]=4
print("The result is:\n")
print(x)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
The result is:

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
J=np.zeros((8,8),dtype=int)
J
J[0::2,0::2]=1
J[1::2,1::2]=1
J

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
import numpy as np
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [ ]:
J=np.random.randint(1,50,size=(6,7,8))
J[5][4][5]


24

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
array = np.array([[0,1], [1,0]])
k = np.tile(array,(4,4))
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix (★☆☆) ***bold text***

In [ ]:
x= np.random.random((5,5))
print("original array:")
print(x)
xmax, xmin = x.max(), x.min()
x= (x - xmin)/(xmax - xmin)
print("after normalization:")
print(x)

original array:
[[0.14604021 0.47125186 0.09112326 0.10731184 0.64273756]
 [0.4909956  0.90927871 0.82798484 0.36658107 0.2400579 ]
 [0.47127408 0.06096209 0.84795324 0.46524845 0.55168293]
 [0.18493033 0.7447461  0.51796098 0.39546142 0.56571687]
 [0.51741676 0.41929801 0.19639033 0.613016   0.05939377]]
after normalization:
[[0.10195079 0.48460453 0.03733386 0.05638183 0.68637972]
 [0.5078356  1.         0.90434721 0.36144575 0.21257481]
 [0.48463068 0.00184533 0.92784262 0.47754073 0.57924213]
 [0.14771006 0.80640602 0.53956387 0.39542723 0.59575487]
 [0.53892352 0.42347407 0.16119424 0.65140845 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("R", np.ubyte),
                  ("G", np.ubyte),
                  ("B", np.ubyte),
                  ("A", np.ubyte)])
                   

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
M = np.dot(np.ones((5,3)), np.ones((3,2)))
print(M)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a=np.arange(12)
b=(a>2)&(a<9)
a[b]*=-1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a=np.array([1,1.7,2.8])
print(a)
b=np.round(a)
print(b)

[1.  1.7 2.8]
[1. 2. 3.]




```
# This is formatted as code
```

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.intersect1d(a,b)
c

array([2, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import numpy as np
data = np.random.random(1000).reshape(10,10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1,2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2022-08-26
2022-08-25
2022-08-27


In [ ]:
import time
time_now=time.time()
time_now

1661871236.257802

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np
print('July, 2016')
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=3
B=6
exp= ((A+B)*(-A/2)) 
exp

-13.5

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
z = np.random.uniform(0,10,5)
print(z)
print(z-z%1)
print(z.astype(int))
print(z//1)
print(np.floor(z))

[8.71466856 6.54400501 3.55998063 8.65994635 8.15656811]
[8. 6. 3. 8. 8.]
[8 6 3 8 8]
[8. 6. 3. 8. 8.]
[8. 6. 3. 8. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np
arr5=np.random.randint(0,4,size=(5,5))
arr5

array([[1, 2, 1, 2, 3],
       [3, 2, 0, 1, 0],
       [0, 1, 0, 0, 3],
       [3, 3, 1, 2, 2],
       [3, 3, 1, 3, 1]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate ():
  for i in range(10):
    yield x
  z = np.romiter(generate(),dtype=float,count=-1)
  print(z)

def generate1 ():
  return np.random.randint(0,50,10)
  z = np.array(generate1(),dtype=np.float64)
print(z)

[[3 1 2 0 2]
 [3 2 3 3 0]
 [1 0 3 2 0]
 [3 0 1 2 1]
 [1 1 3 0 2]]


In [ ]:
def generator_func():
  lst=[]
  for i in range(10):
    n1=int(input())
    lst.append(n1)
    arr=np.array(lst)
  return arr
generator_func()

1
2
3
4
5
6
7
8
9
10


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

z = np.random.rand(10)
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.42663245 0.83545601 0.80248327 0.51496534 0.73902    0.2342618
 0.05626501 0.3694     0.75374769 0.96391516]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
import numpy as np
x = np.random.random(10)
print('original array:')
print(x)
x.sort()
print('sorted array:')
print(x)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.array([5,2,4,6,4,13,5,5])
B = np.array([5,2,9,7,6,4,6])

equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import numpy as np
z=np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(x,y)
print(r)

[0.80624403 1.08053858 0.80575991 1.13772021 0.59392622 1.3596294
 1.07343765 1.15191821 0.93324931 0.5374707 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
z = np.arange(10)
max(z)
print(z.argmax())
z[9] = 0
print(z)

9
[0 1 2 3 4 5 6 7 8 0]




```
# This is formatted as code
```

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)  
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

13


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np
p = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.78443043 0.27626938 0.16755456 0.18049833 0.91227299
  0.64294568 0.52913234 0.36338418 0.6060649 ]
 [0.78443043 0.         0.6774004  0.86241856 0.95343524 0.80401654
  0.14150855 0.51352082 0.76908676 0.21852927]
 [0.27626938 0.6774004  0.         0.22628265 0.35461545 0.63614927
  0.54772467 0.62997885 0.12638573 0.46399707]
 [0.16755456 0.86241856 0.22628265 0.         0.13316099 0.83156913
  0.72418195 0.68257804 0.25411618 0.66136296]
 [0.18049833 0.95343524 0.35461545 0.13316099 0.         0.96396816
  0.81259761 0.7032296  0.38586193 0.76343332]
 [0.91227299 0.80401654 0.63614927 0.83156913 0.96396816 0.
  0.76976924 1.10463166 0.57822041 0.65106037]
 [0.64294568 0.14150855 0.54772467 0.72418195 0.81259761 0.76976924
  0.         0.4172077  0.64753563 0.12227133]
 [0.52913234 0.51352082 0.62997885 0.68257804 0.7032296  1.10463166
  0.4172077  0.         0.7563492  0.49333314]
 [0.36338418 0.76908676 0.12638573 0.25411618 0.38586193 0.57822041
  0.64753563 0.75634

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8




```
# This is formatted as code
```

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
import numpy as np
x, y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp (-( (d-mu)**2 / (2.0 * sigma**2  ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y


array([[-0.26563655, -0.34732906, -0.34005976,  0.11417936,  0.01862091,
         0.21307722,  0.36109181,  0.09397741, -0.19514133,  0.34721998],
       [ 0.18719128,  0.19855069, -0.09023442, -0.04897317,  0.11330584,
        -0.43337351,  0.03249472, -0.24266505, -0.02887975,  0.31258337],
       [-0.05982129, -0.30303695,  0.40335314,  0.16107061,  0.01644571,
         0.02874804,  0.06373301,  0.13728132,  0.01168136, -0.45945494],
       [-0.24585291, -0.19609116,  0.20545882,  0.3139033 ,  0.1695128 ,
        -0.05585699, -0.25642856,  0.07655158, -0.05224365,  0.04104677],
       [ 0.36247406, -0.18139469, -0.41525194,  0.16424203, -0.29471793,
         0.1418446 ,  0.17266788, -0.14407076, -0.12852882,  0.32273558]])

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 8 9]
 [5 0 2]
 [1 4 6]]
[[5 0 2]
 [1 4 6]
 [2 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5523058073256277


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[4. 2. 3. 5. 3. 1. 2. 2. 4. 4.]
[7. 3. 5. 9. 5. 1. 3. 3. 7. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)



[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 65 58 61]
 [67 46 26 56]
 [63 70 61 63]]
[[63 65 58 61]
 [67 46 26 56]
 [63 70 61 63]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.62251528 0.51681321 0.44246223 0.52859202 0.57629974 0.41969693
 0.45709708 0.59982803 0.45053636 0.58952999]
0    0.622515
1    0.516813
2    0.442462
3    0.528592
4    0.576300
5    0.419697
6    0.457097
7    0.599828
8    0.450536
9    0.589530
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.57910546, 1.13890484, 1.24411206, 1.06544191, 0.51817575])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
import numpy as np
a = np.array([[4,3,1],[5,7,0],[9,9,3],[8,2,4]])
print(a)

a[[0,2]] = a[[2,0]]
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 12) ( 1, 31) ( 3, 53) ( 3, 75) (11, 19) (11, 52) (12, 31) (15, 41)
 (15, 45) (19, 52) (21, 31) (21, 37) (21, 51) (21, 82) (31, 82) (34, 78)
 (34, 94) (37, 51) (41, 45) (49, 67) (49, 92) (53, 75) (57, 68) (57, 83)
 (62, 71) (62, 82) (67, 92) (68, 83) (71, 82) (78, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]




```
# This is formatted as code
```

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
import numpy as np
def moving_average(a,n) :
  test = np.cumsum(a, dtype=float)
  test[n:] = test[n:] - test[:-n]
  return test[n - 1:] / n

moving_average(np.arange(20),5)
  

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
import operator
print(operator.not_(True))

False


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.82184771 0.15102297 1.12473357 1.90914424 6.27895665 2.51841628
 8.74436575 4.0222544  8.12725751 2.82981465]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.41987516  4.40714007  0.02703609  3.48746837  2.98715435 10.11147564
  10.38864103 10.55949593  6.320472    9.18775778]
 [ 7.51123233 13.30479012  8.64413042  6.1034308   7.52366321 13.48547679
   0.77515649  2.40991412  1.3479536  13.86264396]
 [ 6.3253909  11.16132838  6.49228751  5.57045691  5.50603102 11.56700859
   0.80293384  2.48355233  0.66267117 11.83459494]
 [ 9.82104737 12.60582154  7.82517541  9.24091282  5.14296304 10.80014104
   2.33076904  1.08622085  2.38366272 11.52124176]
 [11.84419724 10.06911049  5.12954748 12.81791997  0.5659896   5.91232199
   3.09385377  5.47224979  7.65260156  6.9861942 ]
 [ 9.29592138  9.11246936  4.25695991 10.10070981  0.95543604  6.59833588
   0.83945483  2.8036541   5.33170044  7.33902356]
 [ 4.0227749   9.20984769 13.99863011  1.63724274 14.25827613  7.37006507
  15.09310536  1.97989138  7.04956896  8.01411537]
 [ 7.81293609  1.67252337  2.64710587  7.70424814  2.25317253  9.86393037
  14.61318103 14.41335044  9.19328496  8.39488343]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 7 1 6 2 2 2 3 9 4]
 [6 1 4 3 0 9 4 4 2 8]
 [4 9 0 7 2 8 0 0 5 1]
 [3 8 6 4 2 4 3 3 6 4]
 [9 9 9 2 6 0 6 4 9 5]
 [1 5 9 3 9 8 7 4 7 7]
 [1 3 5 9 0 3 6 0 2 4]
 [6 0 6 4 6 1 0 5 9 8]
 [9 1 1 2 9 7 5 3 1 5]
 [3 5 0 4 4 5 1 0 5 0]]
[[0 0 0 0 0]
 [0 7 7 1 6]
 [0 6 1 4 3]
 [0 4 9 0 7]
 [0 3 8 6 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10



> Indented block



In [ ]:
import numpy as np
  
  
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 1]
   [2 1 3]
   [0 0 0]]

  [[3 1 2]
   [1 3 4]
   [0 0 3]]

  [[1 2 1]
   [3 4 0]
   [0 3 1]]

  [[2 1 1]
   [4 0 3]
   [3 1 3]]

  [[1 1 0]
   [0 3 1]
   [1 3 3]]

  [[1 0 1]
   [3 1 0]
   [3 3 1]]

  [[0 1 2]
   [1 0 2]
   [3 1 0]]

  [[1 2 0]
   [0 2 0]
   [1 0 0]]]


 [[[2 1 3]
   [0 0 0]
   [3 2 0]]

  [[1 3 4]
   [0 0 3]
   [2 0 4]]

  [[3 4 0]
   [0 3 1]
   [0 4 4]]

  [[4 0 3]
   [3 1 3]
   [4 4 2]]

  [[0 3 1]
   [1 3 3]
   [4 2 3]]

  [[3 1 0]
   [3 3 1]
   [2 3 1]]

  [[1 0 2]
   [3 1 0]
   [3 1 0]]

  [[0 2 0]
   [1 0 0]
   [1 0 4]]]


 [[[0 0 0]
   [3 2 0]
   [2 2 0]]

  [[0 0 3]
   [2 0 4]
   [2 0 1]]

  [[0 3 1]
   [0 4 4]
   [0 1 1]]

  [[3 1 3]
   [4 4 2]
   [1 1 3]]

  [[1 3 3]
   [4 2 3]
   [1 3 1]]

  [[3 3 1]
   [2 3 1]
   [3 1 1]]

  [[3 1 0]
   [3 1 0]
   [1 1 3]]

  [[1 0 0]
   [1 0 4]
   [1 3 0]]]


 [[[3 2 0]
   [2 2 0]
   [0 0 1]]

  [[2 0 4]
   [2 0 1]
   [0 1 4]]

  [[0 4 4]
   [0 1 1]
   [1 4 4]]

  [[4 4 2]
   [1 1 3]
   [4 4 4]]

  [[4 2 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  9  5 12  9]
 [ 9  2 11 13  5]
 [ 5 11  7 42  6]
 [12 13 42  6 18]
 [ 9  5  6 18  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9999 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.72 s ± 11.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
141 ms ± 1.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
122 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 3]
 [0 3 1]
 [4 0 4]
 [2 3 0]
 [4 0 3]
 [2 2 0]
 [0 1 2]
 [4 3 1]
 [0 1 0]
 [3 3 4]]
[[4 1 3]
 [0 3 1]
 [4 0 4]
 [2 3 0]
 [4 0 3]
 [2 2 0]
 [0 1 2]
 [4 3 1]
 [0 1 0]
 [3 3 4]]
[[4 1 3]
 [0 3 1]
 [4 0 4]
 [2 3 0]
 [4 0 3]
 [2 2 0]
 [0 1 2]
 [4 3 1]
 [0 1 0]
 [3 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.05524033, 0.08689113, 0.07279114, 0.0047449 , 0.08274858,
        0.07588401, 0.09979755, 0.12271458, 0.0633192 , 0.05759954],
       [0.30548497, 0.48051736, 0.40254287, 0.0262398 , 0.45760859,
        0.4196468 , 0.55189126, 0.67862486, 0.35016203, 0.31853166],
       [0.21349599, 0.33582186, 0.28132739, 0.01833835, 0.31981148,
        0.29328091, 0.38570333, 0.47427435, 0.24471969, 0.222614  ],
       [0.37943076, 0.59683155, 0.49998253, 0.03259141, 0.56837748,
        0.52122664, 0.68548224, 0.84289302, 0.43492236, 0.39563554],
       [0.02793714, 0.04394416, 0.03681325, 0.00239968, 0.04184911,
        0.03837744, 0.05047143, 0.06206144, 0.03202293, 0.02913028],
       [0.19157753, 0.30134487, 0.25244505, 0.01645565, 0.28697818,
        0.26317136, 0.34610528, 0.4255832 , 0.21959567, 0.19975944],
       [0.34264451, 0.53896805, 0.45150866, 0.02943163, 0.51327263,
        0.47069312, 0.61902395, 0.76117358, 0.39275614, 0.35727822],
       [0.22048121, 0.34680937, 0.2905319

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23210675  0.13989664]
